steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-world:latest'
      - .
    id: build-image-hello-world
    waitFor:
      - '-'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/hello-world:latest'
    id: push-image-to-container-registry
    waitFor:
      - build-image-hello-world
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - hello-world
      - '--image'
      - 'gcr.io/$PROJECT_ID/hello-world:latest'
      - '--region'
      - asia-south1
      - '--platform'
      - managed
      - '--port'
      - '80'
      - '--allow-unauthenticated'
      - '--min-instances=1'
      - '--max-instances=2'
      - '--cpu=1'
      - '--memory=2Gi'
    id: deploy-to-cloud-run
    waitFor:
      - push-image-to-container-registry
images:
  - 'gcr.io/$PROJECT_ID/hello-world:latest'
